### ISSUE TITLE
Backdoor Found, but it saids it's in the backdoor buster itself

### ISSUE THREAD

**Issue by BadWorksFun** [SnowboiTheGr8/backdoor-buster#3] opened 2018-05-21 15:06 UTC
> Backdoor Blocked: scriptenforcer.net - find the source of this attempt below
stack traceback:
	addons/backdoor-buster-master/lua/autorun/!sh_backdoor-buster.lua:82: in function 'http'
	addons/backdoor-buster-master/lua/autorun/!sh_backdoor-buster.lua:92: in function 'onsuccess'
	lua/includes/modules/http.lua:29: in function <lua/includes/modules/http.lua:25>

**Comment by drizmans** [comment] 2018-06-06 13:34
Duplicate of #2

**Closed as completed by drizmans** 2018-06-06 13:34 UTC
